from flappyBird.wrappers.clip_reward import ClipReward
from flappyBird.wrappers.discrete_actions import DiscreteActions
from flappyBird.wrappers.reacher_weighted_reward import ReacherRewardWrapper
from flappyBird.wrappers.relative_position import RelativePosition
